<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>Tabungan_Ceritanya_V2</RootNamespace>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="Microsoft.Data.Sqlite" Version="9.0.6" />
    <PackageReference Include="WinForms.DataVisualization" Version="1.10.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Graph.cs">
      <SubType>Form</SubType>
    </Compile>
  </ItemGroup>

</Project>